name: insider
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  insider:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Insider
        uses: insidersec/insider-action@v0
        with:
            technology: javascript
            # Relative path under $GITHUB_WORKSPACE to use as a target
            # target: .
